apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-editor
spec:
  replicas: {{ .Values.defaultReplicaCount }}
  selector:
    matchLabels:
      app: swagger-editor
  template:
    metadata:
      labels:
        app: swagger-editor
    spec:
      containers:
      - name: swagger-editor
        image: swaggerapi/swagger-editor
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: {{ .Values.swaggerTargetPort }}
