apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: swagger-route
  namespace: default
  labels:
    app: swagger-editor
  annotations:
      konghq.com/strip-path: 'true'
spec:
  parentRefs:
  - name: {{ .Values.kong.gateway.name }}
  hostnames:
  - "local.swagger"
  rules:
  - matches:
    backendRefs:
    - name: swagger-service
      kind: Service
      port: {{ .Values.swaggerServicePort }}