apiVersion: v1
kind: Service
metadata:
  name: swagger-service
spec:
  selector:
    app: swagger-editor
  ports:
  - port: {{ .Values.swaggerServicePort }}
    targetPort: {{ .Values.swaggerTargetPort }}
    