apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: proximity-route
spec:
  parentRefs:
    - name: {{.Values.gateway.name}}
  hostnames:
    - "local.proximity"
  rules:
    - backendRefs:
        - name: {{.Values.services.proximity.name}}
          kind: Service
          port: {{.Values.services.proximity.port}}