apiVersion: v1
kind: Service
metadata:
  name: {{.Values.services.proximity.name}}
spec:
  type: ClusterIP
  selector:
    app: {{.Values.services.proximity.name}}
  ports:
    - port: {{.Values.services.proximity.port}}
      targetPort: 8080
      name: proximity-port