apiVersion: v1
kind: Service
metadata:
  name: {{.Values.services.gauth.name}}
spec:
  type: ClusterIP
  selector:
    app: {{.Values.services.gauth.name}}
  ports:
    - name: gauth-port
      port: {{.Values.services.gauth.port}}
      targetPort: 8080
