kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: local
nodes:
  - role: control-plane
  - role: worker
  - role: worker
    extraPortMappings:
    - containerPort: 30007
      hostPort: 80
      protocol: TCP
    - containerPort: 30010
      hostPort: 8001
      protocol: TCP
    labels:
      app: kong