apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deployment
spec:
  replicas: {{.Values.services.payment.replicas}}
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: {{.Values.services.payment.name}}:local
          imagePullPolicy: {{.Values.services.payment.imagePullPolicy}}