apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: finhamper-route
    namespace: default
    labels:
      app: finhamper
    annotations:
      konghq.com/strip-path: 'true'
spec:
    parentRefs:
    - name: {{ .Values.kong.gateway.name }}
    hostnames:
    - "local.finhamper"
    rules:
    - matches:
      backendRefs:
      - name: finhamper
        kind: Service
        port: {{ .Values.finhamperServicePort }}
