apiVersion: v1
kind: Service
metadata:
  name: finhamper
spec:
  type: ClusterIP
  selector:
    app: finhamper
  ports:
  - port: {{ .Values.finhamperServicePort }}
    targetPort: {{ .Values.finhamperTargetPort }}
