apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: jokrhat-route
    namespace: default
    labels:
      app: jokrhat
    annotations:
      konghq.com/strip-path: 'true'
spec:
    parentRefs:
    - name: {{ .Values.kong.gateway.name }}
    hostnames:
    - "local.jokrhat"
    rules:
      backendRefs:
      -  name: jokrhat
         kind: Service
         port: {{ .Values.jokrhatServicePort }}